name: Tests

on:
  push:

jobs:
  testrun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i --frozen-lockfile

      - name: Test script run
        run: bun ci:test
